[package]
name = "lotto_longshot"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scan-rules="^0.1"
rand = "0.8.5"
chrono = "0.4"
thousands = "0.2.0"
